# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

ruby "~> 2.3.0"

source 'https://rubygems.org/'

group :test do
  git 'https://github.com/Azure/terramodtest.git' do
    gem 'terramodtest', :tag => 'v0.2.0'
  end
end
